Using TensorFlow backend.
Traceback (most recent call last):
  File "whale-tale.py", line 37, in <module>
    model, history = trainModel(createModel(input_shape, nClasses), train_data, train_labels, epochs, batch_size);
  File "/zhome/jblack33/bio465/whale-tale/model.py", line 11, in createModel
    base_model = applications.VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
  File "/apps/python/2.7.11/gcc-5.3.0/lib/python2.7/site-packages/keras/applications/vgg16.py", line 168, in VGG16
    cache_subdir='models')
  File "/apps/python/2.7.11/gcc-5.3.0/lib/python2.7/site-packages/keras/utils/data_utils.py", line 209, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- [Errno 110] Connection timed out
